---
# An Ansible Playbook to delete a virtual machine using Azure Resource Manager
# Extra variables required when running the playbook:
#   - instance_name: a variable to get the name of virtual machine & it's corresponding resources
#
# Variable to change: resource_group: change this variable to create your own resource group
#
# Command to run the playbook:
#     ansible-playbook delete-vm.yml --extra-vars "instance_name=MongoDB"
- name: Delete Azure Virtual Machine
  hosts: localhost
  connection: local
  # Defining a global resource group name
  vars:
    resource_group: "Paychex"
  tasks:
  - name: Remove a VM and all resources that were autocreated
    azure_rm_virtualmachine:
      resource_group: "{{ resource_group }}"
      name: "{{ instance_name }}-vm"
      remove_on_absent: [network_interfaces, virtual_storage, security_groups]
      state: absent
