# An Ansible Playbook to create a virtual machine using Azure Resource Manager
#
# Variable to change: resource_group: change this variable to create your own resource group
#
# Command to run the playbook:
#     ansible-playbook open-ports.yml --extra-vars "admin_password_here=<enter preferred password here>"

- name: Open Azure VM ports
  hosts: localhost
  connection: local
  become: yes
# Defining a global resource group name
  vars:
    resource_group: 'Paychex'
  tasks:
# Adding security group rules.
# These rules allows you to open particular ports on the VM
  - name: Create Network Security Group that allows SSH
    azure_rm_securitygroup:
      resource_group: "{{ resource_group }}"
      name: "{{ instance_name }}-security-group"
      rules:
        - name: SSH
          protocol: Tcp
          destination_port_range: 22
          access: Allow
          priority: 1001
          direction: Inbound
    tags:
    - SSH
  - name: Create Network Security Group that allows SSH
    azure_rm_securitygroup:
      resource_group: "{{ resource_group }}"
      name: "{{ instance_name }}-security-group"
      rules:
        - name: 'AllowMultipleHTTPPorts'
          protocol: Tcp
          destination_port_range:
            - 80
            - 443
          access: Allow
          priority: 1010
    tags:
    - Port_80
  - name: Create Network Security Group that allows SSH
    azure_rm_securitygroup:
      resource_group: "{{ resource_group }}"
      name: "{{ instance_name }}-security-group"
      rules:
        - name: 'MongoDB_Port'
          protocol: Tcp
          destination_port_range: 27017
          access: Allow
          priority: 1100
    tags:
    - MongoDB_Port
  - name: Open port for Vault
    azure_rm_securitygroup:
      resource_group: "{{ resource_group }}"
      name: "{{ instance_name }}-security-group"
      rules:
        - name: MinecraftPort
          protocol: Tcp
          destination_port_range: 8200
          access: Allow
          priority: 1002
          direction: Inbound
    tags:
    - Vault_Port
  #If the server is a minecraft server open port - GC
  - name: Open port for minecraft
    azure_rm_securitygroup:
      resource_group: "{{ resource_group }}"
      name: "{{ instance_name }}-security-group"
      rules:
        - name: MinecraftPort
          protocol: Tcp
          destination_port_range: 19132
          access: Allow
          priority: 1005
          direction: Inbound
    tags:
    - Minecraft_Port
