---
- hosts: Vault-vm
  gather_facts: false
  vars:
    vault_version: 1.3.0
    consul_version: 1.6.2
    ansible_winrm_server_cert_validation: ignore
    winrm_enable_script: SQBuAHYAbwBrAGUALQBFAHgAcAByAGUAcwBzAGkAbwBuACAALQBDAG8AbQBtAGEAbgBkACAAKAAoAE4AZQB3AC0ATwBiAGoAZQBjAHQAIABTAHkAcwB0AGUAbQAuAE4AZQB0AC4AVwBlAGIAQwBsAGkAZQBuAHQAKQAuAEQAbwB3AG4AbABvAGEAZABTAHQAcgBpAG4AZwAoACcAaAB0AHQAcABzADoALwAvAHIAYQB3AC4AZwBpAHQAaAB1AGIAdQBzAGUAcgBjAG8AbgB0AGUAbgB0AC4AYwBvAG0ALwBhAG4AcwBpAGIAbABlAC8AYQBuAHMAaQBiAGwAZQAvAGQAZQB2AGUAbAAvAGUAeABhAG0AcABsAGUAcwAvAHMAYwByAGkAcAB0AHMALwBDAG8AbgBmAGkAZwB1AHIAZQBSAGUAbQBvAHQAaQBuAGcARgBvAHIAQQBuAHMAaQBiAGwAZQAuAHAAcwAxACcAKQApADsAIABFAG4AYQBiAGwAZQAtAFcAUwBNAGEAbgBDAHIAZQBkAFMAUwBQACAALQBSAG8AbABlACAAUwBlAHIAdgBlAHIAIAAtAEYAbwByAGMAZQA=
  tasks:
    - name: Ping
      win_ping:
    - name: Download Consul
      win_get_url:
        url: "https://releases.hashicorp.com/consul/{{ consul_version }}/consul_{{ consul_version }}_windows_amd64.zip"
        dest: D:\
    - name: Unzipping Consul
      win_unzip:
        src: D:\consul_{{ consul_version }}_windows_amd64.zip
        dest: C:\hashicorp\consul
    - name: Download Vault
      win_get_url:
        url: "https://releases.hashicorp.com/vault/{{ vault_version }}/vault_{{ vault_version }}_windows_amd64.zip"
        dest: D:\
    - name: Unzipping Vault
      win_unzip:
        src: D:\vault_{{ vault_version }}_windows_amd64.zip
        dest: C:\hashicorp\vault
    - name: Copying configuration files
      win_copy:
        src: vault-config.hcl
        dest: C:\hashicorp\vault\vault-config.hcl
    - name: Ensure that consul & vault is in the Windows path
      win_path:
        elements:
          - C:\hashicorp\consul
          - C:\hashicorp\vault
        state: present
    - name: Download PsExec
      win_get_url:
        url: "https://download.sysinternals.com/files/PSTools.zip"
        dest: D:\
    - name: Unzipping PsExec
      win_unzip:
        src: D:\PSTools.zip
        dest: C:\hashicorp\PsExecTools
        force: no
    - name: Starting a Windows service for Consul
      win_command: C:\hashicorp\PsExecTools\PsExec.exe -accepteula -nobanner -i 1 -s C:\hashicorp\consul\consul.exe agent -dev
      async: 2
      poll: 0
      ignore_errors: yes
    - name: Starting a Windows service for Consul
      win_command: C:\hashicorp\PsExecTools\PsExec.exe -accepteula -nobanner -i 1 -s C:\hashicorp\vault\vault.exe server -config C:\hashicorp\vault\vault-config.hcl
      async: 2
      poll: 0
      ignore_errors: yes


        



      
      
   


    


