---
- hosts: Vault-vm
  tasks:
    - name: Downloading the vault (from archive).
      become: yes
      unarchive:
        # TODO: Make the following link a variable dependent for the Vault version
        src: https://releases.hashicorp.com/vault/1.3.0/vault_1.3.0_linux_amd64.zip
        dest: /usr/bin
        remote_src: True
    
    - name: Creating vault config directory.
      file: state=directory path=/etc/opt/vault
      become: yes
    - name: Copying vault config file to the server.
      copy: src=vault_config.hcl dest=/etc/opt/vault
      become: yes
    - name: Copying the vault service file (systemd) to the server
      copy: src=vault.service dest=/usr/lib/systemd/system/vault.service
    # Starting Vault service (systemd)
    - name: Starting Vault service
      become: yes
      systemd:
        state: started
        name: vault
        daemon_reload: yes
    
    - name: Initializing Vault
      command: vault operator init
      register: keys
      environment:
        VAULT_ADDR: "http://localhost:8200"
      
      
    
    #- name: Create vault config dir
