- name: Creating vault user group
  group: 
    name: "{{ vault_group }}"
  become: true
- name: Create vault user
  user:
    name: "{{ vault_user }}"
    group: "{{ vault_group }}"
    system: yes
    shell: "/sbin/nologin"
    comment: "vault User -nologin"
    createhome: "no"
    state: present