---
- hosts: MongoDB-vm
  become: yes
  become_user: root
  tasks:
    - name: Checking if I can connect to the server.
      ping:
    - name: Copying MongoDB repository to the server
      copy: src=mongodb-org-4.0.repo dest=/etc/yum.repos.d/mongodb-org-4.0.repo
    - name: Installing MongoDB
      yum: 
        name: mongodb-org
        state: latest
      notify:
        - start MongoDB
    - name: Updating packages
      yum: name=* state=latest
    - name: Installing required dependencies
      yum:
        state: present
        name:
          - gcc
          - epel-release
    - name: Installing pip
      shell: curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py; python get-pip.py
    - name: Installing the latest pymongo
      pip: name=pymongo state=latest use_mirrors=no
    - name: MONGOD | Create admin user
      mongodb_user:
        database: admin
        name: "{{ mongo_db_user }}"
        password: "{{ mongo_db_pass }}"
        roles: "root"

  handlers:
    - name: start MongoDB
      service:
        name: mongod
        state: started
          
          
        
