---
- hosts: MongoDB-vm
  become: yes
  become_user: root
  tasks:
    - name: Checking if I can connect to the server.
      ping:
    - name: Copying MongoDB repository to the server
      copy: src=mongodb-org-4.0.repo dest=/etc/yum.repos.d/mongodb-org-4.6.repo
    - name: Installing MongoDB
      yum: 
        name: mongodb-org
        state: latest
      notify:
        - start MongoDB

  handlers:
    - name: start MongoDB
      service:
        name: mongod
        state: started
          
          
        
