---
- name: Install Apache
  hosts: Apache-vm
  tasks:
  - name: Installing the latest version of Apache
    yum: pkg=httpd state=latest
    become: yes
    become_user: root
    notify:
    - start apache
  - name: Enabling it on System boot
    become: yes
    become_user: root
    service: 
      name: httpd 
      enabled: yes

  handlers:
    - name: start apache
      become: yes
      become_user: root
      copy:
        src: temp-homepage.yml
        dest: /var/www/html
      service: 
        name: "httpd"
        state: started
