---
  - host: vm3
    become: yes
    become_user: root
    tasks:
      - name: Checking if I can connect to the server.
        ping:
      - name: Removing minecraft files
        raw: cd /home/vmadmin; rm -fr *
